services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - spring-boot-mysql-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dataxet
      MYSQL_USER: dataxet
      MYSQL_PASSWORD: dataxet
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dataxet?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: dataxet
      SPRING_DATASOURCE_PASSWORD: dataxet
      SPRING_FLYWAY_URL: jdbc:mysql://mysql:3306/dataxet?useSSL=false&allowPublicKeyRetrieval=true


volumes:
  mysql-data:

networks:
  spring-boot-mysql-network:
    driver: bridge
